services:
  # 1. Django 서비스
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # 코드 수정 시 바로 반영되도록 연결
    ports:
      - "8000:8000"
    depends_on:
      - db

  # 2. PostgreSQL 서비스
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data # DB 데이터 영구 보존
    environment:
      - POSTGRES_DB=radius_collector
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
    ports:
      - "5433:5432" # 로컬 PostgreSQL과 충돌 방지를 위해 5433

volumes:
  postgres_data:
